[core]
shell=kiosk-shell.so
gbm-format=xrgb8888
repaint-window=7
xwayland=false
idle-time=0
require-input=false

[shell]
# background-image=/data/nerves_weston/logo.jpg
background-type=scale-crop
background-color=0xFF000000
panel-color=0xFF000000
locking=false
animation=zoom
startup-animation=fade
allow-zap=false

[input-method]
path=/usr/libexec/weston-keyboard
overlay-keyboard=true

[keyboard]
keymap_rules=evdev
keymap_layout=us,de
repeat-rate=30
repeat-delay=300
vt-switching=false

[libinput]
# touchpad settings
# enable-tap=true
# tap-and-drag=true
# natural-scroll=true
# scroll-method=two-finger

[output]
name=HDMI-A-1
mode=off

[output]
name=HDMI-A-2
mode=off

[output]
name=DSI-1
transform=rotate-270

[input-device]
device-name=seeed-tp
output-name=DSI-1

[terminal]
font-size=18
